Hmm separation
ScazLab/task-models pull request #7
Opened 2017-12-08 00:18 UTC by elenacorinagrigore

New branch with separate files for task_hmm.

2017-12-08 19:15 UTC, omangin requested changes
OK, overall this is what we have already discussed about.

The main issue is the design of how probabilities are added to the combinations. To summarize, it makes sense to have probabilities only for the alternative and parallel combinations. I am not sure it makes sense to have a public interface for accessing and changing these.

I think the simplest solution is probably to have:
– a `BaseCombination` class,
– a `LeafCombination` that inherit the base one,
– a `Combination` class with children,
– `Sequential`, `Alternative` (the only one implementing the probabilities), and a `Parallel` (implementing `to_alternatives`).

Since it does not matter much at the end, this is the way to go for now.

2017-12-08 19:15 UTC, omangin commented on task_models/task.py
> +from task_models.state import State
That's a matter of taste here but I'd stick with the relative imports.

2017-12-08 19:15 UTC, omangin commented on task_models/task.py
> +import itertools as iter
Check the imports here. You are not using any of them in this file. The convention used in the package is to put first the docstring and then the imports. The future import here is an exception so the other ones would have to go with the other imports below.

2017-12-08 19:15 UTC, omangin commented on task_models/task.py
> +# from task_models import State
Do not leave commented code in your commits.

2017-12-08 19:15 UTC, omangin commented on task_models/task.py
> +class PredAction(AbstractAction):
This one was supposed to be in the other file.

2017-12-08 19:15 UTC, omangin commented on task_models/task.py
> +                assert (len(unique_transitions[node]) == 1)
This indeed makes more sense but then the parenthesis are useless. I was using it like a function everywhere but we can switch to this convention.

2017-12-08 19:15 UTC, omangin commented on task_models/task.py
> -
The convention in the package is to use a blank line after class names except when the next line is a `pass`.

2017-12-08 19:15 UTC, omangin commented on task_models/task.py
> -
…

2017-12-08 19:15 UTC, omangin commented on task_models/task.py
> -
…

2017-12-08 19:15 UTC, omangin commented on task_models/task.py
> +            raise ValueError("Length of probabilities array should be equal \
Whether the list is a probability distribution should also be checked in the parent class (non-negativity and sum to one).

2017-12-08 19:15 UTC, omangin commented on task_models/task.py
> +    def proba(self):
First, this is useless because the property is already defined in the parent.
Second, it does not make sense for the sequential combination to have probabilities.

2017-12-08 19:15 UTC, omangin commented on task_models/task.py
> +    def proba(self, probabilities):
In such a situation it's probably better to remove the ability to set property.

2017-12-08 19:15 UTC, omangin commented on task_models/task.py
> -
…

2017-12-08 19:15 UTC, omangin commented on task_models/task.py
> +    def proba(self, probabilities):
In the current design all these should go to the parent. (However, see my comment in the review main message.)

2017-12-08 19:15 UTC, omangin commented on task_models/task.py
> -
…

2017-12-08 19:15 UTC, omangin commented on task_models/task.py
> +class TrajectoryElement(object):
This should also go to the other file.
Why do you have a probability for each element? It only makes sense at the level of the trajectory.

2018-02-02 23:10 UTC, omangin requested changes
Quickly: the `task` part is better this way.

The `task_hmm` seems overly complicated, but that's not the priority for you to focus on right now. However, it seems that this code belongs (and hence should be moved) to the other repository since it is very specific to your experiment.

2018-02-06 15:39 UTC, omangin requested changes
The refactorization is good but I meant in my previous comment that since `task_hmm` is specific to your experiment it should be moved to your other repo.

See also the minor comments on the code.

2018-02-06 15:39 UTC, omangin commented on task_models/task_hmm.py
> +                 feats='cum', supp_bhvs=None):
This is an ambiguous name. Why not using `cumulative` which is more self explanatory.

If I am not mistaken it appears from the following that `share_feats` and `feats` serve the same purpose. If so, please remove one.

2018-02-06 15:39 UTC, omangin commented on task_models/task_hmm.py
> +                        # keys = [self.obj_names.get(key.name) if re.search(regexp, key.name) is None
If the code is not used any more, don't leave it there.

2018-02-06 15:39 UTC, omangin commented on task_models/task_hmm.py
> +                # traj_bin_feats = \
Same as above. Only leave commented code if it is meant as a comment.

2018-02-19 20:59 UTC, omangin approved these changes
Looks good to merge!

Just check the Codacy issue with the assert.

2018-05-17 14:31 UTC, alecive commented
@elenacorinagrigore can you please fix the `codacy` issue https://app.codacy.com/app/Baxter-collaboration/task-models/pullRequest?prid=1141888 so that I can merge this branch for good? Thanks!

2018-06-01 18:12 UTC, merged